steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.dashboard', '-t', 'asia-south1-docker.pkg.dev/project-41b01091-4313-42ff-8d8/second-unit/second-unit-dashboard', '.']
images:
  - 'asia-south1-docker.pkg.dev/project-41b01091-4313-42ff-8d8/second-unit/second-unit-dashboard'
timeout: '900s'
options:
  logging: CLOUD_LOGGING_ONLY
